field: 7d98f61f-8eb8-4451-8a78-13b36a78eda3
fieldLayouts:
  d6e31844-79dc-40d2-bcfe-f3ec8990febc:
    tabs:
      -
        elements:
          -
            fieldUid: c6f121ca-3f1f-4ad4-8db4-34e6b99c6ad9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0c1a1fd0-1a9d-4418-a650-6b409a61c99f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6b4f7c75-0571-4f1c-8b3f-fda308c47100
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0c1a1fd0-1a9d-4418-a650-6b409a61c99f:
    contentColumnType: text
    fieldGroup: null
    handle: itemDescription
    instructions: ''
    name: 'Item Description'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  6b4f7c75-0571-4f1c-8b3f-fda308c47100:
    contentColumnType: string
    fieldGroup: null
    handle: itemImage
    instructions: ''
    name: 'Item Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:452eb0c3-c1e9-4278-a2d2-7a149d7041a9'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:452eb0c3-c1e9-4278-a2d2-7a149d7041a9'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:452eb0c3-c1e9-4278-a2d2-7a149d7041a9'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c6f121ca-3f1f-4ad4-8db4-34e6b99c6ad9:
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: ''
    name: 'Item Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: item
name: Item
sortOrder: 1
