contentColumnType: string
fieldGroup: e4d1a852-2b7c-4c34-ab2b-1b2195f090a2
handle: matrixRewards
instructions: ''
name: 'Matrix Rewards'
searchable: false
settings:
  contentTable: '{{%matrixcontent_matrixrewards}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
