enableVersioning: false
handle: home
name: Home
propagationMethod: all
siteSettings:
  a0e385e0-70a7-4da0-9d79-35d28731e42c:
    enabledByDefault: true
    hasUrls: true
    template: pages/index
    uriFormat: __home__
type: single
